# Generated by Django 6.0.5 on 2026-05-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationsession',
            name='meditation_type',
            field=models.CharField(choices=[('mindfulness', 'Mindfulness'), ('breathing', 'Breathing'), ('body_scan', 'Body Scan'), ('loving_kindness', 'Loving Kindness'), ('walking', 'Walking'), ('other', 'Other')], default='mindfulness', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meditationsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
