# Generated by Django 6.0.5 on 2026-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0004_rename_compeleted_meditationsession_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditationsession',
            name='completed',
            field=models.BooleanField(),
        ),
    ]
